name: pluto
description: private underground events

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  scrollable_positioned_list: ^0.3.8
  chewie: ^1.9.0
  circle_flags: ^5.0.0
  seo_renderer: ^0.6.0
  sa3_liquid: ^1.0.1
  firebase_analytics: ^12.1.0
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.2
  flutter_local_notifications: ^19.5.0
  file_picker: ^10.3.2
  http: ^1.2.2
  url_launcher: ^6.1.7
  carousel_slider_plus: ^7.0.1
  firebase_messaging: ^16.1.0
  flutter_native_splash: ^2.3.1
  flutter_list_view: ^1.1.21
  intl: any
  go_router: ^16.1.0
  flutter_improved_scrolling: ^0.0.3
  flutter_glow: ^0.3.2
  flutter_widget_from_html: ^0.16.1
  animated_text_kit: ^4.2.2
  sensors_plus: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro-SemiBold.ttf
    - family: FjallaOne
      fonts:
        - asset: assets/fonts/FjallaOne-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf

  assets:
    - assets/home/
    - assets/home/constant/
    - assets/what_i_do/
    - assets/what_i_do/constant/
    - assets/experience/
    - assets/gallery/
    - assets/contact_me/
    - assets/contact_me/constant/
    - assets/projects/
    - assets/projects/constant/
    - assets/achievements/
    - assets/events/
    - assets/portfolio.json
    - assets/test.html
